version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    # env_file:
    #   - .env
    ports:
      - "8000:8000"
    volumes:
      - './:/home/apps'
    links:
      - database
    depends_on:
      - database

  database:
    image: bitnami/postgresql:14.8.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Rick1998@
      - POSTGRES_DB=salvaapp
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
