# Generated by Django 4.2.2 on 2023-07-03 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaAmbulancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14)])),
                ('endereco', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('telefone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salva_vida.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Ambulancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('nome_motorista', models.CharField(max_length=100)),
                ('tipo_ambulancia', models.CharField(choices=[('Ambulância tipo A', 'Ambulância tipo A'), ('Ambulância tipo B', 'Ambulância tipo B'), ('Ambulância tipo C', 'Ambulância tipo C'), ('Ambulância tipo D', 'Ambulância tipo D')], max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salva_vida.empresaambulancias')),
            ],
        ),
    ]
