# Generated by Django 4.2.2 on 2023-07-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salva_vida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('duracao', models.IntegerField()),
                ('ambulancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salva_vida.ambulancia')),
                ('empresa_ambulancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salva_vida.empresaambulancias')),
                ('hospital_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_destino', to='salva_vida.hospital')),
                ('hospital_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_origem', to='salva_vida.hospital')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salva_vida.paciente')),
            ],
        ),
    ]
